### PR TITLE
add chess app

### PR DESCRIPTION
**Pull request by frankiebee**
adds [patch-chess](https://github.com/frankiebee/patch-chess) to patchless so that you'll make a move.

### CODE REVIEW

**Comment by dominictarr** [comment]
@frankiebee btw, the patchless naming convention should be patchapp-chess. can you rename the module?

**Comment by dominictarr** [comment]
electron crashes when I try and move and I get this very weird error in my terminal:
can you confirm this works for you?
```
Error: async hook stack has become corrupted (actual: 7001, expected: 0)
 1: 0x7fce0f2e1dbd [/home/dominic/c/patchless/node_modules/electron/dist/libnode.so]
 2: node::MakeCallback(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/home/dominic/c/patchless/node_modules/electron/dist/libnode.so]
 3: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/home/dominic/c/patchless/node_modules/electron/dist/libnode.so]
 4: 0x7fce0f2f9cfd [/home/dominic/c/patchless/node_modules/electron/dist/libnode.so]
 5: 0x7fce0f468a94 [/home/dominic/c/patchless/node_modules/electron/dist/libnode.so]
 6: uv_run [/home/dominic/c/patchless/node_modules/electron/dist/libnode.so]
 7: atom::NodeBindings::UvRunOnce() [electro]
 8: 0x33b5bf1 [electro]
 9: 0x361bd76 [electro]
10: 0x361b288 [electro]
11: 0x33b5bf1 [electro]
12: 0x33d9c6b [electro]
13: 0x33da038 [electro]
14: 0x33d9836 [electro]
15: 0x33d709a [electro]
16: 0x339de4e [electro]
17: 0x1ca7f63 [electro]
18: 0x1dfdbb1 [electro]
19: 0x1dfe8d2 [electro]
20: 0x1a6c435 [electro]
21: 0x1dfec02 [electro]
22: main [electro]
23: __libc_start_main [/usr/lib/libc.so.6]
24: 0x513f39 [electro]
```

**Comment by dominictarr** [comment]
@happy0 have you seen this error before? I don't know what async hooks are

**Comment by Happy0** [comment]
@dominictarr I have seen that before, but I forget when and what the context was.

I'll try to reproduce it the next time I have a game where it's me to move =p.

By the way - when starting patchless, I encountered an error in ssb-names which I tried to fix ( https://github.com/ssbc/ssb-names/pull/3 ).

**Comment by Happy0** [comment]
I wasn't able to reproduce it. Doesn't mean there's not an issue, of course.. Just that it'll be harder for me to debug.

I searched 'async hook' on scuttlebutt and people have seen it while doing other operations (not just making chess moves.)

There's some suggestions it might be something to do with node versions ( see replies %vygFEvGNphk/OuLuc8B8Bt+QV9oyoR4jLhkqQB3iqNE=.sha256 , for example)

There was another thread ( %ibuxXkAmggv2VrRtwjpIMw8k9slUwWn/CrccQpOfYKg=.sha256 ) but nobody could work out what was going on...

**Comment by dominictarr** [comment]
Hmm, weird. yeah I figured it was a version thing. it seems to work for @frankiebee 

Although _something_ in ssb-chess must be causing this. my go to method for diagnosing something like this would be to comment out sections of the chess code until it stopped. (I don't have time to do that this week I think though)

**Comment by Happy0** [comment]
@dominictarr that area of the code uses a web worker - that's bound to have some funkiness in it at particular versions in electron / node, right?

https://github.com/Happy0/ssb-chess/blob/master/ctrl/game_move.js

Which version of node / electron are you using? I could try using those versions and see if I can reproduce

**Comment by dominictarr** [comment]
progress: I updated to electron@2.0.7 and it's working now.
getting this error when I click on a game though. @frankiebee 
```
Uncaught TypeError: Cannot read property 'stream' of undefined
    at api.sbot.pull.stream.sbot (/home/dominic/c/patchless/node_modules/patchcore/about/obs.js:96)
    at /home/dominic/c/patchless/node_modules/patchcore/sbot.js:240
    at watch (/home/dominic/c/patchless/node_modules/mutant/once-true.js:8)
    at watch (/home/dominic/c/patchless/node_modules/mutant/watch.js:7)
    at onceTrue (/home/dominic/c/patchless/node_modules/mutant/once-true.js:4)
    at Object.stream (/home/dominic/c/patchless/node_modules/patchcore/sbot.js:239)
    at Object.stream (/home/dominic/c/patchless/node_modules/depject/apply.js:18)
    at load (/home/dominic/c/patchless/node_modules/patchcore/about/obs.js:96)
    at get (/home/dominic/c/patchless/node_modules/patchcore/about/obs.js:85)
    at socialValue (/home/dominic/c/patchless/node_modules/patchcore/about/obs.js:70)
    at Array.name (/home/dominic/c/patchless/node_modules/patchcore/about/obs.js:39)
    at module.exports (/home/dominic/c/patchless/node_modules/ssb-embedded-chat/names.js:14)
    at Scroller (/home/dominic/c/patchless/node_modules/ssb-embedded-chat/index.js:109)
    at add (/home/dominic/c/patchless/node_modules/pull-scroll/index.js:42)
    at /home/dominic/c/patchless/node_modules/pull-scroll/index.js:71
    at /home/dominic/c/patchless/node_modules/pull-stream/sinks/drain.js:24
```

**Comment by dominictarr** [comment]
I got it working. your move @Happy0 @frankiebee @mixmix 

just needed ssb-about plugin. on that note: ssb-about brings in lots more data than needed. if names were loaded async this could be much lighter. maybe it would be simple to pass in an adapter to get the names (something like `getName(id, cb)`)

**Comment by mixmix** [comment]
yeah I have been taking this model when building client code (i.e. give me
functions getName, getAvatar)

**Pull request merged**
